#!/usr/bin/env python3
"""Turn the CA certificates in roots/*.pem into letsencrypt_roots.h.

Each file is one PEM X.509 certificate, a Let's Encrypt (ISRG) root as
published at https://letsencrypt.org/certificates/; roots/README.md lists
them with their fingerprints. A verified TLS link to a broker configured by
name trusts these when no certificate is installed in the settings
(src/net/mqtt_tls.c). The DER goes into flash as it is and mbedTLS parses it
in place, so the header costs flash only.
"""

import argparse
import base64
import hashlib
import pathlib
import sys


def certificate(path: pathlib.Path) -> bytes:
    lines = path.read_text().splitlines()
    if lines.count("-----BEGIN CERTIFICATE-----") != 1:
        sys.exit(f"{path}: one PEM certificate per file (BEGIN CERTIFICATE)")
    try:
        first = lines.index("-----BEGIN CERTIFICATE-----")
        last = lines.index("-----END CERTIFICATE-----")
        der = base64.b64decode("".join(lines[first + 1 : last]), validate=True)
    except ValueError:
        sys.exit(f"{path}: not a PEM certificate")
    # one DER SEQUENCE whose stated length is the file's: the same check the
    # firmware makes before storing a certificate (src/pem.c)
    if len(der) < 4 or der[0] != 0x30:
        sys.exit(f"{path}: not a DER certificate")
    if der[1] == 0x81:
        total = 3 + der[2]
    elif der[1] == 0x82:
        total = 4 + (der[2] << 8 | der[3])
    else:
        total = -1
    if total != len(der):
        sys.exit(f"{path}: DER length does not match the file")
    return der


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", required=True, type=pathlib.Path)
    ap.add_argument("pem", nargs="*", type=pathlib.Path)
    args = ap.parse_args()

    out = [
        "// generated by tools/letsencrypt_roots.py from roots/*.pem; do not edit",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    const char *name; // the file's stem, for the log",
        "    const uint8_t *der;",
        "    size_t len;",
        "} letsencrypt_root_t;",
        "",
        f"#define LETSENCRYPT_ROOT_COUNT {len(args.pem)}",
        "",
    ]
    seen = {}
    table = []
    for n, path in enumerate(sorted(args.pem)):
        der = certificate(path)
        if der in seen:
            sys.exit(f"{path}: same certificate as {seen[der]}")
        seen[der] = path
        fingerprint = ":".join(f"{b:02X}" for b in hashlib.sha256(der).digest())
        out.append(f"// {path.name}: {len(der)} bytes, SHA-256 {fingerprint}")
        out.append(f"static const uint8_t letsencrypt_root_{n}[{len(der)}] = {{")
        for i in range(0, len(der), 16):
            out.append("    " + " ".join(f"0x{b:02x}," for b in der[i : i + 16]))
        out.append("};")
        out.append("")
        table.append(f'    {{"{path.stem}", letsencrypt_root_{n}, sizeof letsencrypt_root_{n}}},')
    if not table:
        table.append("    {NULL, NULL, 0}, // no roots: a verified link needs an installed certificate")
    out.append(f"static const letsencrypt_root_t letsencrypt_roots[{max(len(args.pem), 1)}] = {{")
    out.extend(table)
    out.append("};")
    text = "\n".join(out) + "\n"
    if not args.out.exists() or args.out.read_text() != text:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text)


if __name__ == "__main__":
    main()
