#!/usr/bin/env python3
"""Turn the Ed25519 public keys in keys/*.pem into update_keys.h.

Each file is a PEM SubjectPublicKeyInfo, the form Cloud KMS
(gcloud kms keys versions get-public-key) and a YubiKey (ykman piv keys
export) hand out. The firmware installs an image over the network only when
one of these keys signed it; with no keys it accepts unsigned images.
"""

import argparse
import base64
import pathlib
import sys

# DER SubjectPublicKeyInfo for Ed25519 (RFC 8410): this prefix, then the key
SPKI_PREFIX = bytes.fromhex("302a300506032b6570032100")


def public_key(path: pathlib.Path) -> bytes:
    lines = path.read_text().splitlines()
    try:
        first = lines.index("-----BEGIN PUBLIC KEY-----")
        last = lines.index("-----END PUBLIC KEY-----")
        der = base64.b64decode("".join(lines[first + 1 : last]), validate=True)
    except ValueError:
        sys.exit(f"{path}: not a PEM public key (BEGIN PUBLIC KEY)")
    if len(der) != len(SPKI_PREFIX) + 32 or not der.startswith(SPKI_PREFIX):
        sys.exit(f"{path}: not an Ed25519 public key")
    return der[len(SPKI_PREFIX) :]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", required=True, type=pathlib.Path)
    ap.add_argument("pem", nargs="*", type=pathlib.Path)
    args = ap.parse_args()

    out = ["// generated by tools/update_keys.py from keys/*.pem; do not edit", ""]
    out.append(f"#define UPDATE_KEY_COUNT {len(args.pem)}")
    out.append("static const uint8_t update_keys[] = {")
    seen = {}
    for path in sorted(args.pem):
        key = public_key(path)
        if key in seen:
            sys.exit(f"{path}: same key as {seen[key]}")
        seen[key] = path
        out.append(f"    // {path.name}")
        for i in range(0, 32, 8):
            out.append("    " + " ".join(f"0x{b:02x}," for b in key[i : i + 8]))
    if not args.pem:
        out.append("    0, // no keys: signing is not enforced")
    out.append("};")
    text = "\n".join(out) + "\n"
    if not args.out.exists() or args.out.read_text() != text:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text)


if __name__ == "__main__":
    main()
