concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize

name: Kiri Diff

jobs:
  get-changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get changed PCB files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.kicad_pcb
            **/*.kicad_sch
          dir_names: true
          matrix: true
    outputs:
      any-changed: ${{ steps.changed-files.outputs.any_changed }}
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}

  kiri-diff:
    if: ${{ fromJson(needs.get-changed-files.outputs.any-changed) }}
    needs: get-changed-files

    strategy:
      matrix: 
        file: ${{ fromJSON(needs.get-changed-files.outputs.matrix) }}
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get KiCad Project File
        id: kicad-project-file
        run: |
          PROJECT_NAME="$(basename "${{ matrix.file }}")"
          PROJECT_FILE="${{ matrix.file }}/${PROJECT_NAME}.kicad_pro"
          echo "project-file=$PROJECT_FILE" >> "$GITHUB_OUTPUT"

      - name: Kiri
        uses: usa-reddragon/kiri-github-action@v1
        with:
          project-file: ${{ steps.kicad-project-file.outputs.project-file }}